Update publish-docker.yml

diff --git a/.github/workflows/publish-docker.yml b/.github/workflows/publish-docker.yml
--- a/.github/workflows/publish-docker.yml
+++ b/.github/workflows/publish-docker.yml
@@ -1,48 +1,77 @@
-name: Create and publish Docker image
+name: CI/CD
 
 on:
-  release:
-    types: [created]
-
-env:
-  REGISTRY: ghcr.io
-  IMAGE_NAME: ${{ github.repository }}
+  push:
+    branches:
+      - main
+      - master
+      - dev
+      - preprod
+  workflow_dispatch:
+  repository_dispatch:
+    types: [restart-trigger]
 
 jobs:
-  build-and-push-image:
+  precommit:
     runs-on: ubuntu-latest
-    permissions:
-      contents: read
-      packages: write
-
     steps:
       - name: Checkout repository
-        uses: actions/checkout@v4
+        uses: actions/checkout@v3
 
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v3.6.0
-
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3.10.0
-
-      - name: Docker Login
-        uses: docker/login-action@v3.4.0
+      - name: Setup Node.js
+        uses: actions/setup-node@v3
         with:
-          registry: ${{ env.REGISTRY }}
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
+          node-version: '18' # Specify your Node.js version
 
-      - name: Docker Metadata action
-        id: meta
-        uses: docker/metadata-action@v5.7.0
-        with:
-          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
+      - name: Install dependencies
+        run: npm install
 
-      - name: Build and push Docker image
-        uses: docker/build-push-action@v5.4.0
+      - name: Set up
+        uses: actions/setup-python@v4
         with:
-          context: .
-          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
-          push: true
-          tags: ${{ steps.meta.outputs.tags }}
-          labels: ${{ steps.meta.outputs.labels }}
+          python-version: "3.10"
+
+      - name: Install
+        shell: bash
+        run: |
+          pip install pre-commit -q --root-user-action=ignore
+          pre-commit autoupdate
+
+        # This step will fail if pre-commit exits non-zero for *any* reason
+      - name: Run Pre-Commit
+        run: |
+          success=false
+          for i in {1..5}; do
+            echo "Running pre-commit attempt $i..."
+            if pre-commit run --all-files --show-diff-on-failure; then
+              echo "Pre-commit checks passed"
+              success=true
+              break
+            else
+              exit_code=$?
+              echo "Attempt $i failed with exit code $exit_code."
+              if [ $i -lt 5 ]; then
+                sleep 5
+              fi
+            fi
+          done
+
+          if [ "$success" = false ]; then
+            echo "Pre-commit failed"
+            exit 1
+          fi
+          echo "Pre-commit finished successfully."
+        shell: bash
+
+  # precommit:
+  #   needs: setup
+  #   uses: deepalertai/global_actions/.github/workflows/precommit.yml@main
+
+  build:
+    needs:
+      - precommit
+    uses: deepalertai/global_actions/.github/workflows/build.yml@main
+    with:
+      project_id: ${{ vars[format('PROJECT_ID_{0}', github.ref_name)] }}
+    secrets:
+      gcp_provider: ${{ secrets[format('GCP_ID_PROVIDER_{0}', github.ref_name)] }}
